/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
export const iPersonSchema = z.object({
  name: z.string(),
  age: z.union([z.number(), z.null()]).optional()
});