import { z } from 'zod'
export const activityTypeZodSchema = z.enum([
  'message',
  'contactRelationUpdate',
  'conversationUpdate',
  'typing',
  'endOfConversation',
  'event',
  'invoke',
  'invokeResponse',
  'deleteUserData',
  'messageUpdate',
  'messageDelete',
  'installationUpdate',
  'messageReaction',
  'suggestion',
  'trace',
  'handoff',
  'command',
  'commandResult',
])

export enum ActivityType {
  Message = 'message',
  ContactRelationUpdate = 'contactRelationUpdate',
  ConversationUpdate = 'conversationUpdate',
  Typing = 'typing',
  EndOfConversation = 'endOfConversation',
  Event = 'event',
  Invoke = 'invoke',
  InvokeResponse = 'invokeResponse',
  DeleteUserData = 'deleteUserData',
  MessageUpdate = 'messageUpdate',
  MessageDelete = 'messageDelete',
  InstallationUpdate = 'installationUpdate',
  MessageReaction = 'messageReaction',
  Suggestion = 'suggestion',
  Trace = 'trace',
  Handoff = 'handoff',
  Command = 'command',
  CommandResult = 'commandResult',
}
